# Generated by Django 2.2 on 2019-04-15 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedCardSet',
            fields=[
                ('simplecardset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='custom_cards.SimpleCardSet')),
                ('serif', models.ImageField(height_field=200, upload_to='uploads/cards/%Y/%m/%d/', width_field=100)),
                ('loveMaker', models.ImageField(height_field=200, upload_to='uploads/cards/%Y/%m/%d/', width_field=100)),
                ('doctor', models.ImageField(height_field=200, upload_to='uploads/cards/%Y/%m/%d/', width_field=100)),
            ],
            bases=('custom_cards.simplecardset',),
        ),
    ]
