# Generated by Django 2.2 on 2019-04-18 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='mafia_percentage',
        ),
        migrations.AddField(
            model_name='game',
            name='people_as_mafia',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
