# Generated by Django 2.2 on 2019-04-19 19:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190418_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended', models.BooleanField(default=False)),
                ('citizen', models.ImageField(upload_to='cards/%Y/%m/%d')),
                ('mafia', models.ImageField(upload_to='cards/%Y/%m/%d')),
                ('sheriff', models.ImageField(upload_to='cards/%Y/%m/%d')),
                ('doctor', models.ImageField(upload_to='cards/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='people_as_doctor',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='game',
            name='people_as_sheriff',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='game',
            name='card_set',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.CardSet'),
        ),
    ]
