# Generated by Django 2.2 on 2019-04-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_room_roomqueryitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomQueryItem',
            new_name='RoomParticipant',
        ),
    ]
