# Generated by Django 2.2 on 2019-04-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190419_2234'),
        ('game', '0003_auto_20190418_1659'),
    ]

    operations = [
    ]
