# Generated by Django 2.2 on 2019-04-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190419_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
