# Generated by Django 2.2 on 2019-04-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_merge_20190424_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomParticipant',
        ),
    ]
