# Generated by Django 2.2 on 2019-04-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_cardset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='as_doctor',
            field=models.IntegerField(default=0, verbose_name='Кол-во игр за доктора'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='as_sheriff',
            field=models.IntegerField(default=0, verbose_name='Кол-во игр за шерифа'),
        ),
    ]
