# Generated by Django 2.2 on 2019-04-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190424_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='doctor',
            field=models.ImageField(blank=True, null=True, upload_to='cards/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='sheriff',
            field=models.ImageField(blank=True, null=True, upload_to='cards/%Y/%m/%d'),
        ),
    ]
