# Generated by Django 2.2 on 2019-04-26 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_auto_20190426_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GamePlayers',
            new_name='GamePlayer',
        ),
        migrations.AlterField(
            model_name='cardset',
            name='doctor',
            field=models.ImageField(null=True, upload_to='cards/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='sheriff',
            field=models.ImageField(null=True, upload_to='cards/%Y/%m/%d'),
        ),
    ]
