# Generated by Django 2.2 on 2019-04-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190426_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='doctor',
            field=models.ImageField(blank=True, null=True, upload_to='cards/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='sheriff',
            field=models.ImageField(blank=True, null=True, upload_to='cards/%Y/%m/%d'),
        ),
    ]
