# Generated by Django 2.2 on 2019-04-28 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20190426_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='people_as_mafia',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
